# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-30 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='colonia',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
