# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-18 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_auto_20190829_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sec_last_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
