# Generated by Django 2.2.4 on 2020-01-20 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_auto_20200120_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='category2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meds', to='dashboard_app.Category'),
        ),
    ]
